[package]
name = "fluxy"
version = "0.0.0"
description = "Software for fast file transfer between terminals in the same network segment."
authors = ["thep0y"]
license = "AGPL-3.0"
repository = "https://github.com/alley-rs/fluxy"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "6"
lazy_static = "1"
salvo = { version = "0", features = ["serve-static"] }
tokio = { version = "1", features = ["macros"] }
tokio-util = "0"
local-ip-address = "0"
qrcode-generator = "5"
bytes = '1'
futures = "0"
time = { version = "0", features = ['macros'] }
thiserror = "2"
tracing-subscriber = { version = "0", features = [
  'time',
  'env-filter',
  'json',
] }
tracing = { version = "0", features = ["log", "release_max_level_info"] }
tracing-appender = '0'
rust-embed = "8"
sys-locale = "0"

tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
tauri-plugin-clipboard-manager = "2"


[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = true
opt-level = "z"
strip = true
